spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/salm
    username: salm_user
    password: your_password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  mail:
    host: smtp.yourmail.com
    port: 587
    username: your_email
    password: your_password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
